version: '3'
services:
    web:
      build:
          context: ./parn
          dockerfile: Dockerfile
      command: python3 django101/manage.py runserver 0.0.0.0:8000
      ports:
        - "8000:8000"
