version: '3'
services:
    web:
      build:
          context: ./parn
          dockerfile: Dockerfile
      command: bash -c "chmod +x ./entrypoint.sh && ./entrypoint.sh"
      ports:
        - "8000:8000"
      volumes:
        - ./parn:/app
    db:
      image: postgres
      volumes:
        - postgres-data:/var/lib/postgresql/data
      ports:
        - "5432:5432"

volumes:
  postgres-data:
